/**
 * Scribe Project status enumeration
 * - 'draft': Initial state
 * - 'collecting_answers': Waiting for user input via form
 * - 'drafting': AI is generating the content
 * - 'reviewing': Content is ready for user review
 * - 'needs_input': AI needs more information
 * - 'typesetting': Converting to PDF/LaTeX
 * - 'completed': Final PDF is ready
 * - 'failed': Something went wrong
 */
export type ScribeProjectStatus =
	| "draft"
	| "collecting_answers"
	| "drafting"
	| "reviewing"
	| "needs_input"
	| "typesetting"
	| "completed"
	| "failed";

/**
 * Represents a Scribe project (AI-assisted document generation).
 * @interface ScribeProject
 */
export interface ScribeProject {
	/** Unique identifier */
	id: string;
	/** User ID who owns this project */
	userId: string;
	/** Optional Task ID associated with this project */
	taskId: string | null;
	/** Optional Subject ID associated with this project */
	subjectId: string | null;
	/** Project title */
	title: string;
	/** Current status of the project */
	status: ScribeProjectStatus;
	/** Rubric or instructions for the project */
	rubricContent: string | null;
	/** Questions generated by AI for the user */
	formQuestions: unknown | null;
	/** Answers provided by the user */
	userAnswers: unknown | null;
	/** Generated content in Markdown format */
	contentMarkdown: string | null;
	/** Generated content in LaTeX format */
	currentLatex: string | null;
	/** Feedback from the review process */
	reviewFeedback: unknown | null;
	/** ID of the Cloudflare Workflow execution */
	workflowId: string | null;
	/** ID of the final generated PDF file */
	finalPdfFileId: string | null;
	/** ISO 8601 timestamp of creation */
	createdAt: string;
	/** ISO 8601 timestamp of last update */
	updatedAt: string;
}

/**
 * Input data for creating a new Scribe project.
 * @interface CreateScribeProjectData
 */
export interface CreateScribeProjectData {
	/** User ID */
	userId: string;
	/** Project title */
	title?: string;
	/** Optional Task ID */
	taskId?: string | null;
	/** Optional Subject ID */
	subjectId?: string | null;
	/** Initial rubric content */
	rubricContent?: string | null;
}

/**
 * Input data for updating a Scribe project.
 * @interface UpdateScribeProjectData
 */
export interface UpdateScribeProjectData {
	/** Project title */
	title?: string;
	/** Status update */
	status?: ScribeProjectStatus;
	/** Rubric content update */
	rubricContent?: string | null;
	/** Form questions update */
	formQuestions?: unknown | null;
	/** User answers update */
	userAnswers?: unknown | null;
	/** Content markdown update */
	contentMarkdown?: string | null;
	/** Current LaTeX update */
	currentLatex?: string | null;
	/** Review feedback update */
	reviewFeedback?: unknown | null;
	/** Workflow ID update */
	workflowId?: string | null;
	/** Final PDF file ID update */
	finalPdfFileId?: string | null;
}
