/**
 * Scribe Project status enumeration
 * Scribe v2:
 * - 'needs_input': Scribe Agent needs more information (returns formSchema)
 * - 'processing': Scribe Agent is processing (server-side iteration)
 * - 'blocked': PDF generated + exam generated (UX-gated until unlock_pdf)
 * - 'available': Unlocked by user (passed exam)
 * - 'failed': Something went wrong
 */
export type ScribeProjectStatus =
	| "needs_input"
	| "processing"
	| "blocked"
	| "available"
	| "failed";

/**
 * Represents a Scribe project (AI-assisted document generation).
 * @interface ScribeProject
 */
export interface ScribeProject {
	/** Unique identifier */
	id: string;
	/** User ID who owns this project */
	userId: string;
	/** Optional Task ID associated with this project */
	taskId: string | null;
	/** Optional Subject ID associated with this project */
	subjectId: string | null;
	/** Template ID for Typst generation (e.g., "default", "apa", "ieee") */
	templateId: string;
	/** Project title */
	title: string;
	/** Current status of the project */
	status: ScribeProjectStatus;
	/** Rubric or instructions for the project (text) */
	rubricContent: string | null;
	/** R2 key of the rubric file (PDF, image, etc.) */
	rubricFileR2Key: string | null;
	/** MIME type of the rubric file */
	rubricMimeType: string | null;
	/** Questions generated by AI for the user */
	formSchema: unknown | null;
	/** Answers provided by the user */
	userAnswers: unknown | null;
	/** Exam payload generated after PDF generation */
	exam: unknown | null;
	/** Generated content in Markdown format */
	contentMarkdown: string | null;
	/** JSON output from Typesetter Agent (metadata, content, template_config) */
	currentTypstJson: string | null;
	/** Feedback from the review process */
	reviewFeedback: unknown | null;
	/** ID of the Cloudflare Workflow execution */
	workflowId: string | null;
	/** R2 key of the final generated PDF file */
	finalPdfR2Key: string | null;
	/** ISO 8601 timestamp of creation */
	createdAt: string;
	/** ISO 8601 timestamp of last update */
	updatedAt: string;
}

/**
 * Input data for creating a new Scribe project.
 * @interface CreateScribeProjectData
 */
export interface CreateScribeProjectData {
	/** User ID */
	userId: string;
	/** Project title */
	title?: string;
	/** Optional Task ID */
	taskId?: string | null;
	/** Optional Subject ID */
	subjectId?: string | null;
	/** Template ID for Typst generation (defaults to "default") */
	templateId?: string;
	/** Initial rubric content (text) */
	rubricContent?: string | null;
	/** R2 key of the rubric file */
	rubricFileR2Key?: string | null;
	/** MIME type of the rubric file */
	rubricMimeType?: string | null;
}

/**
 * Input data for updating a Scribe project.
 * @interface UpdateScribeProjectData
 */
export interface UpdateScribeProjectData {
	/** Project title */
	title?: string;
	/** Status update */
	status?: ScribeProjectStatus;
	/** Rubric content update */
	rubricContent?: string | null;
	/** R2 key of the rubric file */
	rubricFileR2Key?: string | null;
	/** MIME type of the rubric file */
	rubricMimeType?: string | null;
	/** Form questions update */
	formSchema?: unknown | null;
	/** User answers update */
	userAnswers?: unknown | null;
	/** Exam payload update */
	exam?: unknown | null;
	/** Content markdown update */
	contentMarkdown?: string | null;
	/** JSON output from Typesetter Agent */
	currentTypstJson?: string | null;
	/** Review feedback update */
	reviewFeedback?: unknown | null;
	/** Workflow ID update */
	workflowId?: string | null;
	/** R2 key of the final generated PDF */
	finalPdfR2Key?: string | null;
}
